name: Questions
description: You think somethings is broken in the UI
title: "[Question]: "
labels: ["Question"]
assignees: ["samvanderzwan"]

body:
  - type: markdown
    attributes:
      value: |
        *Please fill this form with as much information as possible*
