name: Questions
description: Questions can be posted in the discusion forum see below.
title: "[Question]: "
labels: ["Question"]
assignees: ["samvanderzwan"]

body:
  - type: checkboxes
    attributes:
      label: Where to post questions
      description: Please post questions in the discusion forum [here](https://github.com/Project-OMOTES/user_feedback/discussions/new?category=q-a).
      options:
        - label: I know that I should ask a question [here](https://github.com/Project-OMOTES/user_feedback/discussions/new?category=q-a)
          required: true
