name: Questions
description: Please post your question here: https://github.com/Project-OMOTES/user_feedback/discussions/new/choose
title: "[Question]: "
labels: ["Question"]
assignees: ["samvanderzwan"]

body:
  - type: markdown
    attributes:
      value: |
        Please note this form is not used, please https://github.com/Project-OMOTES/user_feedback/discussions/new/choose
  - type: checkboxes
    attributes:
      label: Please read the above
      description: Please reac the above and go to https://github.com/Project-OMOTES/user_feedback/discussions/new/choose for submitting a questions
      options:
        - label: I do know that I should ask a question here: https://github.com/Project-OMOTES/user_feedback/discussions/new/choose
          required: true

