name: Questions
description: Please post your question here "https://github.com/Project-OMOTES/user_feedback/discussions/new?category=q-a"
title: "[Question]: "
labels: ["Question"]
assignees: ["samvanderzwan"]

body:
  - type: checkboxes
    attributes:
      label: Please read the above
      description: Please read the above and go to https://github.com/Project-OMOTES/user_feedback/discussions/new?category=q-a for submitting a questions.
      options:
        - label: I do know that I should ask a question here https://github.com/Project-OMOTES/user_feedback/discussions/new?category=q-a
          required: true
