name: Questions
description: You think somethings is broken in the UI
title: "[Question]: "
labels: ["Question"]
assignees: ["samvanderzwan"]

body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered. If so comment on that issue.
      options:
        - label: I have searched the existing issues.
          required: true
  - type: markdown
    attributes:
      value: |
        *Please fill this form with as much information as possible*
